# fly.toml file generated for alura-linguagens-valdir on 2023-04-02T19:35:33-03:00

app = "alura-linguagens-valdir"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gig"
processes = []

[build]
  image = "valdyrtorres/linguagensapi"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
